### ISSUE TITLE
Allow photo UIDs to be added

### ISSUE THREAD

**Issue by codebrewer** [dadoug/gneasy-genkey#22]
GnuPG allows addition of JPEG photo UIDs and it's reasonably straightforward to add support for this to the script. Before creating a pull request I'd like to describe the way I've implemented it and point out some downsides to doing this automatically.

First of all, is it a feature that others think is desirable?

I've implemented it by allowing one or more filenames to be specified along with the normal name and email address UIDs, _e.g._:

`gneasy-genkey "Testy McTesterson <testy@mctesterson.test>,photo1.jpeg,photo2.jpeg"`

`.jpg` and `.jpeg` filename extensions are recognized and relative or absolute paths may be used.

An alternative would be to add a long option like `--photo` that takes a filename as a parameter, but the method I've chosen seems more in keeping with how the script's currently invoked.

There are some downsides to automating this:

- when added interactively in a graphical environment, GnuPG displays images (for instance using `xloadimage`) and asks for confirmation that they should be added; this doesn't happen if the state machine approach is used;
- when added interactively (whether in a graphical environment or not), GnuPG warns that it considers image files larger than 6KB in size to be "large" and asks for confirmation that they should be added;
- the state machine status file that's generated when adding an image doesn't seem to contain anything that's helpful in determining whether or not the image was added successfully; the colon-delimited key listing includes lines for each image but there doesn't seem to be an obviously easy way (by which I mean a simple one-liner) to associate a line from a key listing with a particular image file (in the admittedly unlikely case where more than one image is added).

The change I've been testing automatically confirms that images larger than 6KB in size should be added. I found several online examples where that limit was considered arbitrarily small although I have to say I think it's perfectly possible to produce an acceptable greyscale JPEG that's 240 x 288px and smaller than 6KB.

**Comment by dadoug** [comment]
This is a nifty idea and in keeping with the purpose of this script; that is, to tamp down as many barriers-to-entry as reasonably achievable.

Given the _relatively_ less common usage of photos in public keys -- and, in particular, since photo based services like Facebook, Google+, Github, Gravatar, etc. steadfastly refuse to support public keys -- I am in favor of implementing this via an explicit `--photo` option rather than an expanded comma seperated list of generic inputs.

It is exceptionally helpful to have the pros and cons elucidated as you've done. The downsides seem to me to be rather trivial, espeecially given the add-on nature of this feature request.

Might I also suggest adding an image of "Testy McTesterson" to the `test` directory? Maybe a kitty-cat? (Please use a "Creative Commons", or similar libre-licensed image.) Also, please don't be shy about adding your own test scripts to this directory.

Many thanks, and looking forward to trying out this spiffy new feature!

**Comment by codebrewer** [comment]
Thanks for the feedback - and I'm happy you're in favour. It's simple enough to switch to an explicit `--photo` option so I'll do that. I too think the downsides are outweighed by the convenience so I won't give them any more thought.

Good idea on the sample image. I must say I assumed "Testy McTesterson" was just a random name you'd come up with and I was surprised to find a bunch of hits when I searched just now... Is there some connection with cats I'm missing though?

**Comment by dadoug** [comment]
Testy _is_ a random name that I came up with, around the time that "Boaty McBoatface" was in the news ... or so I thought until I read your message and searched for myself. That is pretty darn funny. :-)  There's no feline connection, other than the notion that The Internet loves cats.

**Comment by codebrewer** [comment]
I'm not much of a cat fan myself, but who am I to go against The Internet... 😸
